name: SmallAmpCI
env:
  SA_mode: dspotFastRank
  SA_maxInputs: 10
  SA_shreds: 15  
  SA_timeBudget: 12
  SA_project_baseline: 'ContainersArray2D'
  SA_project_directory: 'src'
  
on:
  workflow_dispatch:
    inputs:
      testClasses:
        description: 'TestClasses to amplify (comma separated) empty-> all'
        required: false
        default: ''
      parallel_jobs:         
        description: 'Max number of all parallel jobs (0 use Input testClasses length)'
        required: true
        default: '8'

jobs:
  TestAmplification:
    uses: TestAmplification/SmallAmpCI/.github/workflows/SmallAmpCI.yml@main
    with:
      testClasses: ${{github.event.inputs.testClasses }}
      mode: ${{env.SA_mode}}
      parallel_jobs: ${{github.event.inputs.parallel_jobs}}
      maxInputs: ${{env.SA_maxInputs}}
      shreds: ${{env.SA_shreds}}
      timeBudget: ${{env.SA_timeBudget}}
      input_project_baseline: ${{env.SA_project_baseline}}
      input_project_directory: ${{env.SA_project_directory}}
    secrets:
      secret_github_token: ${{secrets.GITHUB_TOKEN}}
